frase = """Um dia descobrimos que beijar uma pessoa para esquecer outra é bobagem.
Você não só não esquece a outra pessoa como pensa muito mais nela...
Um dia nós percebemos que as mulheres têm instinto "caçador" e fazem qualquer homem sofrer ...
Um dia descobrimos que se apaixonar é inevitável...
Um dia percebemos que as melhores provas de amor são as mais simples...
Um dia percebemos que o comum não nos atrai...
Um dia saberemos que ser classificado como "bonzinho" não é bom...
Um dia perceberemos que a pessoa que nunca te liga é a que mais pensa em você..."""
frase = frase.replace('Um dia','One day')
#print(frase)
#print("homem" in frase)
print(frase.find(''))
dividido =frase.split()
print(dividido[76])
print(len(frase.split()))